### ISSUE TITLE
Export-PSGraph fails when a node is called "graph"

### ISSUE THREAD

**Issue by dchristian3188** [KevinMarquette/PSGraph#30]
Steps to reproduce:

```powershell
Graph testGraph {
    node 'cat'
    node 'Graph'
    node 'dog'    
} | Export-PSGraph -ShowGraph
```

**Comment by KevinMarquette** [comment]
Other node names that cause this:

* node
* edge
* subgraph
* digraph

The first error message is coming from graphviz when it parses the graph output.

    Error: <stdin>: syntax error in line 7 near '}'

I suspect all DOT keywords  would cause this failure.

**Comment by dchristian3188** [comment]
What do you think about changing this section in Format-Value?

```powershell
 # Normal value, no quotes
                '^[\w]+$'
                {
                    '"{0}"' -f $value
                }
```

I ran through some quick tests and it seems to resolve the issue.

**Comment by KevinMarquette** [comment]
There are two scenarios that I would need to look at that I may as well document here and get some tests added.

The first one is setting note (or edge) attribute defaults.

     Graph testGraph {
        node @{shape='rect'}
        node 'cat'
        node 'dog'    
     } | Export-PSGraph -ShowGraph

If that first node gets quotes around it, it becomes a real node instead of defining the attributes for the other nodes. In one case you would get two squares and in the other, you would get one square and two circles.  

I did notice that custom format scripts are causing issues like this too, so I opened #32 to track it. I'm going to look to see how easy it would be to pull that special case out of the normal format logic. 

The second is edges to record nodes. 

    graph g {
        node @{shape='record'}
        node struct1 @{shape='record';label=" left|<f1> middle|<f2> right"}
        node struct2 @{shape='record';label="<f0> one| two"}
        node struct3 @{shape='record';label="hello\nworld |{ b |{c|<here> d|e}| f}| g | h"}
        edge struct1:f1 -to struct2:f0
        edge struct1:f2 -to struct3:here
    } | Export-PSGraph -ShowGraph

The edge in this example may need some more analysis. I don't have any documentation on record nodes and edges, but I want to maintain that underlying engine compatibility. 

I am tempted to add a way to turn that off though and that may be a better discussion in another thread. As it stands, it gets in the way of edges to `uri` and `server:port` named nodes.
