### ISSUE TITLE
Export-PSGraph does not support PowerShellCore on MacOS

### ISSUE THREAD

**Issue by larssb** [KevinMarquette/PSGraph#36]
The issue is likely also there on Linux, however only verified on MacOS. The use of $env:temp does not work with PowerShell Core on MacOS (running beta3).

- I get:
`Export-PSGraph : Cannot run a document in PowerShell Core: /Users/"USERNAME"/0xanmbp2.y4x.png.
At /PATH/file.ps1:102 char:40
+ ... graphData | Export-PSGraph -ShowGraph -DestinationPath $destinationPa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (/Users/USERNAME/0xanmbp2.y4x.png:String) [Export-PSGraph], RuntimeException
    + FullyQualifiedErrorId : CantActivateDocumentInPowerShellCore,Export-PSGraph
`

I managed to handle it in my script by looking at type of os --> generating a path+filename --> then use -destinationpath parameter on the Export-PSGraph cmdlet. However, it would be great if it was handled inside PSGraph directly.

Let me know if the above raises some questions and I'll happily answer those.

Thank you.

**Comment by larssb** [comment]
Any feedback on this? Thank you a million.

**Comment by Kyahx** [comment]
You can work around it by adding "$env:TEMP = $env:TMPDIR" to your $PROFILE script.

**Comment by KevinMarquette** [comment]
I was considering the use of the `DestinationPath` as a valid workaround but I held of saying anything because I was not sure that I wanted that to be my official stance on it.

I would use `New-TemporaryFile`, but I am still trying to maintain 4.0 compatibility. I just took a look at the source for it and I see that I can use `[system.io.path]::GetTempPath()` instead.

I just checked in a new change that removes the use of the `TEMP` environment variable. Let me know if this resolved your issues on the mac or makes it worse.
