### ISSUE TITLE
Cylinder Shape

### ISSUE THREAD

**Issue by mieel** [KevinMarquette/PSGraph#95]
I'm trying to use the shape type 'cylinder' but it I get this error:

dot.exe : Warning: using box for unknown shape cylinder
At C:\Program Files\WindowsPowerShell\Modules\PSGraph\2.1.38.27\PSGraph.psm1:904 char:53
+ ...         $null = $standardInput.ToString() | & $graphViz @($arguments)
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Warning: using ... shape cylinder:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by KevinMarquette** [comment]
This is an issue with graphviz. From some other threads, it looks like it is fixed source but I don't see a newer Windows release that contains the fix.

https://gitlab.com/graphviz/graphviz/issues/1342
https://github.com/sverweij/atom-graphviz-preview-plus/issues/13

Closing this issue because there are no action items for this project
